<template>
  <chi-space>
    <chi-button>按钮</chi-button>
    <chi-button>按钮</chi-button>
    <chi-button>按钮</chi-button>
    <chi-button>按钮</chi-button>
    <chi-button>按钮</chi-button>
  </chi-space>
</template>
